### ISSUE TITLE
Refreshing connection error

### ISSUE THREAD

**Issue by ghost** [basiqio/basiq-sdk-php#1]
When calling `UserService->refreshAllConnections` it is crashing while trying to create a Job with a UserService instead of a ConnectionService:

`
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Basiq\Entities\Job::__construct() must be an instance of Basiq\Services\ConnectionService, instance of Basiq\Services\UserService given, called in /app/vendor/basiqio/basiq-sdk-php/src/services/UserService.php on line 168 and defined in /app/vendor/basiqio/basiq-sdk-php/src/entities/Job.php:17
`

**Comment by nenadlukic** [comment]
Thank you very much for raising an issue, the bug has been fixed.

**Comment by ghost** [comment]
Thanks for looking at the issues so promptly. However, I'm getting a new error with the refresh now: 
`
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Basiq\Entities\Job::__construct() must be an instance of Basiq\Services\ConnectionService, null given, called in /app/vendor/basiqio/basiq-sdk-php/src/services/UserService.php on line 185 and defined in /app/vendor/basiqio/basiq-sdk-php/src/entities/Job.php:17
`

**Comment by nenadlukic** [comment]
Hmm, can you show me how you're using the method by providing a code snippet?

**Comment by ghost** [comment]
```
function refreshConnection($basiq_id) {
      $userService = new UserService($this->session);
      return $userService->refreshAllConnections($basiq_id);
}
```
Session is generated by:
```
$this->session = new Session($this->basiq_key);
```

**Comment by nenadlukic** [comment]
Thank you for helping me find the issue, it has been resolved, run ```composer update``` and you should get correct behavior. Let me know if you have any other issues, or any other way I can assist you.

**Comment by ghost** [comment]
that worked! Thank you :)
