### ISSUE TITLE
ResponseParser not being used?

### ISSUE THREAD

**Issue by leoauri** [basiqio/basiq-sdk-php#6]
I'm getting an error wherever the code goes for a "Basiq\Utilities\ResponseParser" class:

`Fatal error: Uncaught Error: Class 'Basiq\Utilities\ResponseParser' not found in .../basiq-sdk-php/src/Session.php`

It seems that Session.php is not using Basiq\Utilities\ResponseParser, although it starts with the use operator: 
`use Basiq\Utilities\ResponseParser;`

If I replace the line
`$body = ResponseParser::parse($response);`
with
`$body = json_decode($response->getBody()->getContents(), true);`
for example, I can create a new Basiq\Session object, otherwise it throws that error

**Comment by leoauri** [comment]
Actually it seems a more general problem with deeply embedded namespaces
Now I'm getting:
`Uncaught Error: Class 'Basiq\Services\UserService' not found`

But the Basiq\Session class is being used

**Comment by leoauri** [comment]
I installed the SDK with
`php composer.phar require basiqio/basiq-sdk-php dev-master`

Requiring with
`require_once plugin_dir_path( dirname( __FILE__ ) ) . 'vendor/autoload.php';`

So if I run
```
use Basiq\Session;
use Basiq\Services\UserService;
echo "Basiq\Session: " . ((class_exists('Basiq\Session') ? 'yes' : 'no' )) . "<br/>";
echo "Basiq\Services\UserService: " . ((class_exists('Basiq\Services\UserService') ? 'yes' : 'no' )) . "<br/>";
```

I get
```
Basiq\Session: yes
Basiq\Services\UserService: no
```

:(

**Comment by slapcevic** [comment]
Can you give us the version you are using? We can't seem to reproduce the problem on our end. And with your own code we're getting yes for both classes.

**Comment by leoauri** [comment]
~~It must be a problem with composer,~~ here's the /vendor/composer/autoload_psr4.php file:
```
<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Basiq\\' => array($vendorDir . '/basiqio/basiq-sdk-php/src'),
);
```

~~I reckon all the directories in /src should have been put here when composer auto-generated it.~~
Please note also that I had to install with a [different method](https://github.com/basiqio/basiq-sdk-php/issues/5) than you suggest in the README

Did you get yes for both classes when installed via composer?

**Comment by nenadlukic** [comment]
Ok I have created a new directory, ran the `composer require basiqio/basiq-sdk-php dev-master` command, created a new php file with the following contents:

```
<?php

require_once(__DIR__."/vendor/autoload.php");

use Basiq\Session;
use Basiq\Services\UserService;

var_dump(class_exists("Basiq\Session"));
var_dump(class_exists("Basiq\Services\UserService"));
```

Both dumps return `bool(true)`. This is weird, I assume it's something related to your autoloading. What version of composer are you using, maybe try updating it?

**Comment by leoauri** [comment]
I installed basiqio/basiq-sdk-php 0.9.2beta 
by running `php composer.phar require basiqio/basiq-sdk-php dev-master`
With composer 1.6.5
~~PHP 7.0~~

**Comment by leoauri** [comment]
Isn't true for both the expected behaviour?

**Comment by leoauri** [comment]
What version of composer are you using?

**Comment by nenadlukic** [comment]
Yes it is expected, I meant that it is weird that you're not getting the same result. 

I've just tried with your version of PHP and still getting the same result, both are true. Can you do a `composer dump-autoload -o`, and then check the `autoload_classmap.php` if it contains the `UserService` class.

**Comment by leoauri** [comment]
I just realised that I'm running it with php5.6.35
Will do that

**Comment by leoauri** [comment]
```
composer dump-autoload -o
```

```
Basiq\Session: yes
Basiq\Services\UserService: yes
```
!

**Comment by leoauri** [comment]
```
composer dump-autoload
```

```
Basiq\Session: yes
Basiq\Services\UserService: no
```
!

**Comment by nenadlukic** [comment]
Can you create a new folder and perform the steps you've mentioned in the original post and test with the code I've provided?

**Comment by leoauri** [comment]
`php composer.phar require basiqio/basiq-sdk-php`

_Using version ^1.0 for basiqio/basiq-sdk-php ..._ 
```
<?php

require_once(__DIR__."/vendor/autoload.php");

use Basiq\Session;
use Basiq\Services\UserService;

var_dump(class_exists("Basiq\Session"));
var_dump(class_exists("Basiq\Services\UserService"));
```
Output: 

_bool(true)
bool(false)_

Tested running composer from PHP 5.6.36 and PHP 7.2.5

**Comment by jbardnz** [comment]
Got this same error, I think the issue is the /src/utilities folder has a lowercase u when it needs to have an uppercase U.
